name: delete--api-v1-task-{taskId}

on:
  workflow_dispatch:
    inputs:
      taskId:
        description: "taskId"
        required: true
        type: string

jobs:
  api-call:
    runs-on: ubuntu-latest
    steps:
      - name: Make API Request
        id: api-request
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.API_BASE_URL }}/api/v1/task/{taskId}
          method: DELETE
          customHeaders: '{"Content-Type": "application/json"}'
          bearerToken: ${{ secrets.API_TOKEN }}
          data: ${{ toJSON(inputs) }}

      - name: Response
        run: echo ${{ toJSON(steps.api-request.outputs.response) }} | jq .
