name: get--api-v1-clouds

on:
  workflow_dispatch:
    inputs:
      all:
        description: "all"
        required: false
        type: boolean

jobs:
  api-call:
    runs-on: ubuntu-latest
    steps:
      - name: Make API Request
        id: api-request
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.API_BASE_URL }}/api/v1/clouds
          method: GET
          customHeaders: '{"Content-Type": "application/json"}'
          bearerToken: ${{ secrets.API_TOKEN }}
          data: ${{ toJSON(inputs) }}

      - name: Response
        run: echo ${{ steps.api-request.outputs.response }}
