name: get--api-v1-organization-members

on:
  workflow_dispatch:
    inputs:
      limit:
        description: "limit"
        required: false
        type: number
      offset:
        description: "offset"
        required: false
        type: number

jobs:
  api-call:
    runs-on: ubuntu-latest
    steps:
      - name: Make API Request
        id: api-request
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.API_BASE_URL }}/api/v1/organization/members
          method: GET
          customHeaders: '{"Content-Type": "application/json"}'
          bearerToken: ${{ secrets.API_TOKEN }}
          data: ${{ toJSON(inputs) }}

      - name: Response
        run: echo ${{ toJSON(steps.api-request.outputs.response) }} | jq .
