name: get--api-v1-environments-props

on:
  workflow_dispatch:
    inputs:
      sort:
        description: "sort"
        required: false
        type: string
      order:
        description: "order"
        required: false
        type: string
      offset:
        description: "offset"
        required: false
        type: number
      limit:
        description: "limit"
        required: false
        type: number
      filter:
        description: "Structure: `[key1=value1,key2=value2&value3]`"
        required: false
        type: string
      search:
        description: "search"
        required: false
        type: string

jobs:
  api-call:
    runs-on: ubuntu-latest
    steps:
      - name: Make API Request
        id: api-request
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.API_BASE_URL }}/api/v1/environments/props
          method: GET
          customHeaders: '{"Content-Type": "application/json"}'
          bearerToken: ${{ secrets.API_TOKEN }}
          data: ${{ toJSON(inputs) }}

      - name: Response
        run: echo ${{ fromJSON(steps.api-request.outputs.response) }} | jq .
