name: get--api-v1-setup-preflight

on:
  workflow_dispatch:
    inputs:
      vendor:
        description: "vendor"
        required: false
        type: string

jobs:
  api-call:
    runs-on: ubuntu-latest
    steps:
      - name: Make API Request
        id: api-request
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.API_BASE_URL }}/api/v1/setup/preflight
          method: GET
          customHeaders: '{"Content-Type": "application/json"}'
          bearerToken: ${{ secrets.API_TOKEN }}
          data: ${{ toJSON(inputs) }}

      - name: Response
        run: echo ${{ fromJSON(steps.api-request.outputs.response) }} | jq .
