name: patch--api-v1-organization

on:
  workflow_dispatch:
    inputs:
      name:
        description: "name"
        required: false
        type: string
      display_name:
        description: "display_name"
        required: false
        type: string
      branding:
        description: "branding"
        required: false
        type: string
      metadata:
        description: "metadata"
        required: false
        type: string

jobs:
  api-call:
    runs-on: ubuntu-latest
    steps:
      - name: Make API Request
        id: api-request
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.API_BASE_URL }}/api/v1/organization
          method: PATCH
          customHeaders: '{"Content-Type": "application/json"}'
          bearerToken: ${{ secrets.API_TOKEN }}
          data: ${{ toJSON(inputs) }}

      - name: Response
        run: echo ${{ steps.api-request.outputs.response }} | jq .
