name: post--api-v1-deployments-{deploymentId}

on:
  workflow_dispatch:
    inputs:
      deploymentId:
        description: "deploymentId"
        required: true
        type: string
      action:
        description: "action (error)"
        required: true
        type: string
      payload:
        description: "payload"
        required: true
        type: string

jobs:
  api-call:
    runs-on: ubuntu-latest
    steps:
      - name: Make API Request
        id: api-request
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.API_BASE_URL }}/api/v1/deployments/${{ inputs.deploymentId }}
          method: POST
          customHeaders: '{"Content-Type": "application/json"}'
          bearerToken: ${{ secrets.API_TOKEN }}
          data: ${{ toJSON(inputs) }}

      - name: Response
        run: echo ${{ toJSON(steps.api-request.outputs.response) }} | jq .
