name: post--api-v1-package-search

on:
  workflow_dispatch:
    inputs:
      query:
        description: "query"
        required: true
        type: string
      sort:
        description: "sort"
        required: false
        type: string
      order:
        description: "order"
        required: false
        type: string
      offset:
        description: "offset"
        required: false
        type: number
      limit:
        description: "limit"
        required: false
        type: number

jobs:
  api-call:
    runs-on: ubuntu-latest
    steps:
      - name: Make API Request
        id: api-request
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.API_BASE_URL }}/api/v1/package/search
          method: POST
          customHeaders: '{"Content-Type": "application/json"}'
          bearerToken: ${{ secrets.API_TOKEN }}
          data: ${{ toJSON(inputs) }}

      - name: Response
        run: echo ${{ steps.api-request.outputs.response }} | jq .
