name: post--api-v1-cloud

on:
  workflow_dispatch:
    inputs:
      provider:
        description: "provider"
        required: true
        type: string
      roleArnId:
        description: "roleArnId"
        required: true
        type: string
      cloudFormationStackId:
        description: "cloudFormationStackId"
        required: true
        type: string
      accountSlug:
        description: "accountSlug"
        required: false
        type: string
      accountName:
        description: "accountName"
        required: false
        type: string
      accountId:
        description: "accountId"
        required: true
        type: string
      environment:
        description: "environment"
        required: false
        type: string
      externalId:
        description: "externalId"
        required: true
        type: string

jobs:
  api-call:
    runs-on: ubuntu-latest
    steps:
      - name: Make API Request
        id: api-request
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.API_BASE_URL }}/api/v1/cloud
          method: POST
          customHeaders: '{"Content-Type": "application/json"}'
          bearerToken: ${{ secrets.API_TOKEN }}
          data: ${{ toJSON(inputs) }}

      - name: Response
        run: echo ${{ steps.api-request.outputs.response }} | jq .
