name: put--api-v1-environment-{idOrSlug}-edit

on:
  workflow_dispatch:
    inputs:
      idOrSlug:
        description: "idOrSlug"
        required: true
        type: string
      color:
        description: "color"
        required: false
        type: string
      name:
        description: "name"
        required: false
        type: string

jobs:
  api-call:
    runs-on: ubuntu-latest
    steps:
      - name: Make API Request
        id: api-request
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.API_BASE_URL }}/api/v1/environment/{idOrSlug}/edit
          method: PUT
          customHeaders: '{"Content-Type": "application/json"}'
          bearerToken: ${{ secrets.API_TOKEN }}
          data: ${{ toJSON(inputs) }}

      - name: Response
        run: echo ${{ steps.api-request.outputs.response }}
